### ISSUE TITLE
Explore Page API

### ISSUE THREAD

**Issue by Liz2107** [CSCI3308-Group7-Book-Tracker/book-tracker#38]
Add API call to Google Books in order to populate the search results. 

As a user, I should see relevant results corresponding to a search.

**Comment by rlodhicode** [comment]
Since json objects aren't all the same, some book queries return errors in query. For example, the book "Stinker From Space" yields an undefined image prop and breaks the app.

![Image](https://github.com/CSCI3308-Group7-Book-Tracker/book-tracker/assets/112054070/4459e379-65a8-4dee-89ab-609fb4b5fda9)

To fix this we should make sure our API's use conditional definitions in the event that the return json objects aren't the same. The changes that will need to be made are for json accesses. Use `?.` instead of just `.` so that the code doesn't break on json reads and instead returns an empty object. This may mean we want some default in the event that an image or some prop isn't readable. So the user knows that there isn't an available metadata option. 

i.e.

`books.blah` --> `books?.blah`.

**Comment by rlodhicode** [comment]
Just putting this in to see if it could work in testing. If it does then it might make our lives easier and our code cleaner

`      <%
      if (books) {
          var rows = '';
          books.forEach(function (item) {
              rows += "<tr><td>" + (item?.volumeInfo?.title ?? "N/A") + "</td><td>" + 
                      (item?.volumeInfo?.authors?.[0] ?? "N/A") + "</td><td>" + 
                      (item?.volumeInfo?.publishedDate ?? "N/A") + "</td><td><img src=\"" + 
                      (item?.volumeInfo?.imageLinks?.smallThumbnail) + "\"></td></tr>";
          });
      }
  %>`
